### ISSUE TITLE
[Bug] Strange design breaks on small screens

### ISSUE THREAD

**Issue by CubexsOne** [sprinteins/poker#14]
Browser:
Google Chrome

When opening Scrum Poker on a small screen,
e.g. iPad 12,9 inch as second screen for the Macbook via Sidecar
(without sidebars) a pagination is generated at different buttons.

<img width="1355" alt="Bildschirmfoto 2022-11-09 um 10 33 11" src="https://user-images.githubusercontent.com/46932387/200837158-86cac456-cc8e-4f3d-acb1-b46e019ed7cf.png">

**Comment by tamasrusz** [comment]
Solved with #19
